<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Ug_student extends Model
{
    use HasFactory;
    protected $fillable = [
        'college_email',
        'cca_sports',
        'eca_sports',
        'major_game',
        'minor_game',
        'aadhar_number',
        'country',
        'state',
        'city',
        'pincode',
        'permanent_address_line_1',
        'permanent_address_line_2',
        'blood_group',
        'nationality',
        'religion',
        'birth_place',
        'uploaded_photo',
        'uploaded_signature',
        'name_in_hindi',
        'marital_status',
        'kashmiri_immigrant',
        'identification_mark',
        'extra_curricular_activities',
        'other_relevent_info',
        'favourite_past_time',
        'hobbies',
        'jee_advanced_rank',
        'jee_advanced_category_rank',
        'bank_name_of_student',
        'account_no_of_student',
        'confirm_account_no_of_student',
        'ifsc_code_of_student',
        'father_name',
        'mother_name',
        'father_occupation',
        'mother_occupation',
        'father_income',
        'mother_income',
        'parent_mobile_no',
        'parent_email_id',
        'guardian_name',
        'guardian_relation',
        'alternate_mobile_no',
        'alternate_email_id',
        'bank_name_of_parent',
        'account_no_of_parent',
        'confirm_account_no_of_parent',
        'ifsc_code_of_parent',
        'name_of_examination_10',
        'university_board_10',
        'year_10',
        'institution_school_10',
        'grade_percentage_10',
        'division_10',
        'major_subjects_10',
        'uploaded_marksheet_10',
        'uploaded_certificate_10',
        'name_of_examination_12',
        'university_board_12',
        'year_12',
        'institution_school_12',
        'grade_percentage_12',
        'division_12',
        'major_subjects_12',
        'migration_certificate_no',
        'uploaded_marksheet_12',
        'uploaded_certificate_12',
        'food_habit',
        'laptop_details',
        'model_no',
        'serial_no'
    ];
}
